/**
 * AgroExpress - Comprehensive Agricultural Sample Data
 * Includes Seeds, Fertilizers, Pesticides, Farm Tools, Nearby Shops, and Dosage Guidelines.
 * Supports English, Hindi (हिन्दी), and Marathi (मराठी).
 */

const AGRO_DATA = {
  categories: [
    { 
      id: 'all', 
      name: 'All Products', 
      hindiName: 'सभी उत्पाद', 
      marathiName: 'सर्व उत्पादने', 
      icon: '🌾',
      thumb: 'images/fertilizers/iffco_urea_45kg.jpg', 
      count: 35 
    },
    { 
      id: 'fertilizers', 
      name: 'Fertilizers (खाद)', 
      hindiName: 'उर्वरक / खाद', 
      marathiName: 'खते / पोषण', 
      icon: '🧪', 
      thumb: 'images/fertilizers/iffco_urea_45kg.jpg',
      count: 11 
    },
    { 
      id: 'seeds', 
      name: 'Seeds (बीज)', 
      hindiName: 'बीज (Seeds)', 
      marathiName: 'बियाणे (Seeds)', 
      icon: '🌱', 
      thumb: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=300&q=80',
      count: 8 
    },
    { 
      id: 'pesticides', 
      name: 'Crop Care (कीटनाशक)', 
      hindiName: 'फसल सुरक्षा', 
      marathiName: 'पीक संरक्षण', 
      icon: '🛡️', 
      thumb: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=300&q=80',
      count: 11 
    },
    { 
      id: 'tools', 
      name: 'Farm Tools (उपकरण)', 
      hindiName: 'कृषि उपकरण', 
      marathiName: 'कृषी अवजारे', 
      icon: '🚜', 
      thumb: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=300&q=80',
      count: 5 
    }
  ],

  shops: [
    {
      id: 'shop-1',
      name: 'Kisan Krishi Seva Kendra',
      hindiName: 'किसान कृषि सेवा केंद्र',
      marathiName: 'किसान कृषी सेवा केंद्र',
      distance: 1.2,
      distanceText: '1.2 km away',
      deliveryTime: '30-45 mins',
      rating: 4.8,
      reviewsCount: 312,
      address: 'Main Mandi Road, Sector 4, Kisan Nagar',
      addressHi: 'मेन मंडी रोड, सेक्टर 4, किसान नगर',
      addressMr: 'मुख्य कृषी उत्पन्न बाजार रस्ता, किसान नगर',
      phone: '+91 98765 43210',
      isVerified: true,
      isOpen: true,
      minOrder: 199,
      deliveryFee: 20,
      image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80',
      specialty: 'Govt. Certified Seeds & Fertilizers',
      specialtyHi: 'सरकारी प्रमाणित बीज एवं उर्वरक',
      specialtyMr: 'शासकीय प्रमाणित बियाणे व खते',
      badge: 'Fastest Delivery',
      badgeHi: 'सबसे तेज़ डिलीवरी',
      badgeMr: 'सर्वात जलद डिलिव्हरी'
    },
    {
      id: 'shop-2',
      name: 'Jai Kisan Agro Chemicals & Seeds',
      hindiName: 'जय किसान एग्रो केमिकल्स',
      marathiName: 'जय किसान अ‍ॅग्रो केमिकल्स व बियाणे',
      distance: 2.8,
      distanceText: '2.8 km away',
      deliveryTime: '45-60 mins',
      rating: 4.6,
      reviewsCount: 189,
      address: 'Near Old Grain Market, Bypass Chowk',
      addressHi: 'पुरानी अनाज मंडी के पास, बाईपास चौक',
      addressMr: 'जुना धान्य बाजार जवळ, बायपास चौक',
      phone: '+91 98234 56781',
      isVerified: true,
      isOpen: true,
      minOrder: 250,
      deliveryFee: 30,
      image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80',
      specialty: 'Bio-Fertilizers & Organic Solutions',
      specialtyHi: 'जैविक खाद एवं कीटनाशक विशेषज्ञ',
      specialtyMr: 'सेंद्रिय खते व जैविक उपाय तज्ज्ञ',
      badge: 'Best Rated',
      badgeHi: 'सर्वश्रेष्ठ रेटिंग',
      badgeMr: 'उत्कृष्ट रेटिंग'
    },
    {
      id: 'shop-3',
      name: 'GreenField Agri Inputs & Machinery',
      hindiName: 'ग्रीनफील्ड एग्री इनपुट्स',
      marathiName: 'ग्रीनफिल्ड अ‍ॅग्री इनपुट्स व यंत्रसामग्री',
      distance: 3.5,
      distanceText: '3.5 km away',
      deliveryTime: '1-2 hours',
      rating: 4.7,
      reviewsCount: 145,
      address: 'Shop 14, APMC Market Yard',
      addressHi: 'दुकान 14, एपीएमसी मार्केट यार्ड',
      addressMr: 'दुकान क्र. 14, एपीएमसी मार्केट यार्ड',
      phone: '+91 97123 45678',
      isVerified: true,
      isOpen: true,
      minOrder: 500,
      deliveryFee: 40,
      image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
      specialty: 'Sprayers, Drip Systems & Machinery',
      specialtyHi: 'स्प्रेयर पंप, ड्रिप सिस्टम एवं कृषि औजार',
      specialtyMr: 'फवारणी पंप, ठिबक सिंचन व कृषी यंत्रे',
      badge: 'Top Farm Tools',
      badgeHi: 'शीर्ष कृषि उपकरण',
      badgeMr: 'सर्वोत्तम कृषी अवजारे'
    },
    {
      id: 'shop-4',
      name: 'Annadata Fertilizer & Pesticide Depot',
      hindiName: 'अन्नदाता खाद एवं बीज भंडार',
      marathiName: 'अन्नदाता खते व कीटकनाशक डेपो',
      distance: 4.9,
      distanceText: '4.9 km away',
      deliveryTime: '2-3 hours',
      rating: 4.5,
      reviewsCount: 98,
      address: 'Kisan Bhawan Link Road, Village Simrol',
      addressHi: 'किसान भवन लिंक रोड, सिमरोल गांव',
      addressMr: 'किसान भवन लिंक रोड, सिमरोल गाव',
      phone: '+91 96543 21098',
      isVerified: true,
      isOpen: false,
      minOrder: 300,
      deliveryFee: 45,
      image: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80',
      specialty: 'Bulk IFFCO Urea & DAP Specialist',
      specialtyHi: 'थोक इफको यूरिया एवं डीएपी उपलब्ध',
      specialtyMr: 'इफको युरिया व डीएपी घाऊक पुरवठादार',
      badge: 'Wholesale Rates',
      badgeHi: 'थोक भाव',
      badgeMr: 'घाऊक दर'
    },
    {
      id: 'shop-5',
      name: 'Sahyadri Shetkari Seva Kendra',
      hindiName: 'सह्याद्री शेतकरी सेवा केंद्र',
      marathiName: 'सह्याद्री शेतकरी सेवा केंद्र',
      distance: 1.8,
      distanceText: '1.8 km away',
      deliveryTime: '30-40 mins',
      rating: 4.9,
      reviewsCount: 220,
      address: 'Taluka Panchayat Road, Agri Hub',
      addressHi: 'तालुका पंचायत रोड, कृषि केंद्र',
      addressMr: 'तालुका पंचायत रस्ता, कृषी केंद्र',
      phone: '+91 94220 11223',
      isVerified: true,
      isOpen: true,
      minOrder: 200,
      deliveryFee: 25,
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
      specialty: 'Soybean & Onion Seeds Specialist',
      specialtyHi: 'सोयाबीन एवं प्याज बीज विशेषज्ञ',
      specialtyMr: 'सोयाबीन व कांदा बियाणे तज्ज्ञ',
      badge: 'Certified Seeds Hub',
      badgeHi: 'प्रमाणित बीज केंद्र',
      badgeMr: 'प्रमाणित बियाणे केंद्र'
    },
    {
      id: 'shop-6',
      name: 'Balaji Krishi Rasayan & Khad Bhandar',
      hindiName: 'बालाजी कृषि रसायन एवं खाद भंडार',
      marathiName: 'बालाजी कृषी रसायने व खत भांडार',
      distance: 3.1,
      distanceText: '3.1 km away',
      deliveryTime: '40-55 mins',
      rating: 4.7,
      reviewsCount: 164,
      address: 'Opp. State Bank, Main Chowk',
      addressHi: 'स्टेट बैंक के सामने, मुख्य चौक',
      addressMr: 'स्टेट बँकेसमोर, मुख्य चौक',
      phone: '+91 98901 23456',
      isVerified: true,
      isOpen: true,
      minOrder: 250,
      deliveryFee: 30,
      image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
      specialty: 'Micronutrients & Foliar Nutrition',
      specialtyHi: 'सूक्ष्म पोषक तत्व एवं घुलनशील खाद',
      specialtyMr: 'सूक्ष्म अन्नद्रव्ये व फवारणी खते',
      badge: 'Nutrition Expert',
      badgeHi: 'पोषक तत्व विशेषज्ञ',
      badgeMr: 'अन्नद्रव्य तज्ज्ञ'
    }
  ],

  products: [
    // --- FERTILIZERS (Real Certified Fertilizer Images) ---
    {
      id: 'fert-1',
      name: 'IFFCO Neem Coated Urea (45 Kg Bag)',
      hindiName: 'इफको नीम लेपित यूरिया (45 किलो बोरी)',
      marathiName: 'इफको नीम कोटेड युरिया (45 किलो गोणी)',
      category: 'fertilizers',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 266,
      originalPrice: 290,
      discount: 'Govt. Subsidized',
      packageSize: '45 Kg Bag',
      rating: 4.9,
      reviews: 420,
      inStock: true,
      stockCount: 85,
      featured: true,
      image: 'images/fertilizers/iffco_urea_45kg.jpg',
      description: 'Official Neem coated urea essential for nitrogen enrichment, vegetative growth, and lush green leaves in all crops.',
      specs: {
        'Nitrogen Content': '46% Minimum',
        'Coating': 'Pure Neem Oil',
        'Recommended For': 'Wheat, Paddy, Sugarcane, Maize, Vegetables',
        'Dosage': '40-50 Kg / Acre during vegetative phase'
      }
    },
    {
      id: 'fert-2',
      name: 'IFFCO DAP (Di-Ammonium Phosphate 50 Kg)',
      hindiName: 'इफको डीएपी 50 किलो बोरी',
      marathiName: 'इफको डीएपी 50 किलो खत गोणी',
      category: 'fertilizers',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 1350,
      originalPrice: 1400,
      discount: '4% OFF',
      packageSize: '50 Kg Bag',
      rating: 4.9,
      reviews: 290,
      inStock: true,
      stockCount: 42,
      featured: true,
      image: 'images/fertilizers/iffco_dap_50kg.jpg',
      description: 'Prime source of Phosphorus and Nitrogen for strong root system development, early seedling vigor, and maximum tillering.',
      specs: {
        'Nutrient Ratio': '18% Nitrogen : 46% Phosphorus',
        'Solubility': 'Water soluble phosphate',
        'Recommended For': 'Basal application in Wheat, Mustard, Gram, Potato, Soybean',
        'Dosage': '50 Kg / Acre at sowing time'
      }
    },
    {
      id: 'fert-3',
      name: 'NPK 19:19:19 100% Water Soluble (1 Kg)',
      hindiName: 'एनपीके 19:19:19 घुलनशील खाद (1 किलो)',
      marathiName: 'एनपीके 19:19:19 पाण्यात विद्राव्य खत (1 किलो)',
      category: 'fertilizers',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 180,
      originalPrice: 220,
      discount: '18% OFF',
      packageSize: '1 Kg Pouch',
      rating: 4.7,
      reviews: 115,
      inStock: true,
      stockCount: 120,
      featured: false,
      image: 'images/fertilizers/npk_191919_1kg.jpg',
      description: 'Balanced foliar spray fertilizer providing equal parts Nitrogen, Phosphorus, and Potassium for instant plant uptake and quick recovery.',
      specs: {
        'Composition': 'N-P-K (19-19-19) Balanced',
        'Application': 'Foliar spray or Drip irrigation',
        'Recommended For': 'Vegetables, Fruits, Flowers, Cotton, Sugarcane',
        'Dosage': '5-10 grams per liter of water'
      }
    },
    {
      id: 'fert-4',
      name: 'Pure Organic Vermicompost (Khad 25 Kg)',
      hindiName: 'शुद्ध जैविक केंचुआ खाद (25 किलो)',
      marathiName: 'शुद्ध सेंद्रिय गांडूळ खत (25 किलो)',
      category: 'fertilizers',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 320,
      originalPrice: 380,
      discount: '15% OFF',
      packageSize: '25 Kg Bag',
      rating: 4.8,
      reviews: 178,
      inStock: true,
      stockCount: 65,
      featured: false,
      image: 'images/fertilizers/vermicompost_25kg.jpg',
      description: '100% natural earthworm compost enriched with beneficial microbes, humic acid, and micro-nutrients for high soil aeration and water retention.',
      specs: {
        'Type': 'Organic Bio-Compost',
        'Moisture': '20-25%',
        'Recommended For': 'Horticulture, Polyhouse, Kitchen Gardens, Organic Farming',
        'Dosage': '200-300 Kg / Acre'
      }
    },
    {
      id: 'fert-5',
      name: 'MOP (Muriate of Potash 50 Kg Bag)',
      hindiName: 'एमओपी पोटाश खाद (50 किलो)',
      marathiName: 'एमओपी म्युरिएट ऑफ पोटॅश खत (50 किलो)',
      category: 'fertilizers',
      shopId: 'shop-4',
      shopName: 'Annadata Fertilizer Depot',
      price: 1650,
      originalPrice: 1750,
      discount: '6% OFF',
      packageSize: '50 Kg Bag',
      rating: 4.6,
      reviews: 84,
      inStock: true,
      stockCount: 28,
      featured: false,
      image: 'images/fertilizers/potash_mop_50kg.jpg',
      description: 'Supplies Potassium (K) to boost disease resistance, improve grain weight, and enhance crop quality and drought tolerance.',
      specs: {
        'Potash Content': '60% K2O',
        'Form': 'Red granular',
        'Recommended For': 'Potato, Sugarcane, Paddy, Banana, Pulses',
        'Dosage': '25-30 Kg / Acre'
      }
    },
    {
      id: 'fert-6',
      name: 'Mahadhan 24:24:0 Complex Fertilizer (50 Kg)',
      hindiName: 'महाधन 24:24:0 कॉम्प्लेक्स खाद (50 किलो)',
      marathiName: 'महाधन 24:24:0 खत गोणी (50 किलो)',
      category: 'fertilizers',
      shopId: 'shop-5',
      shopName: 'Sahyadri Shetkari Seva Kendra',
      price: 1480,
      originalPrice: 1550,
      discount: '5% OFF',
      packageSize: '50 Kg Bag',
      rating: 4.8,
      reviews: 132,
      inStock: true,
      stockCount: 50,
      featured: false,
      image: 'images/fertilizers/mahadhan_24240_50kg.jpg',
      description: 'High grade Ammonium Phosphate Sulphate ideal for oilseeds, pulses, and sugarcane. Contains vital Sulphur for protein and oil synthesis.',
      specs: {
        'Nitrogen': '24%',
        'Phosphate': '24%',
        'Sulphur': '10%',
        'Recommended For': 'Soybean, Cotton, Groundnut, Sugarcane'
      }
    },
    {
      id: 'fert-7',
      name: 'Multiplex Chelated Zinc 12% EDTA (500g)',
      hindiName: 'मल्टीप्लेक्स चिलेटेड जिंक 12% (500 ग्राम)',
      marathiName: 'मल्टीप्लेक्स चिलेटेड झिंक 12% (500 ग्रॅम)',
      category: 'fertilizers',
      shopId: 'shop-6',
      shopName: 'Balaji Krishi Rasayan',
      price: 340,
      originalPrice: 399,
      discount: '15% OFF',
      packageSize: '500 Gram Pack',
      rating: 4.9,
      reviews: 98,
      inStock: true,
      stockCount: 60,
      featured: false,
      image: 'images/fertilizers/chelated_zinc_500g.jpg',
      description: '100% water soluble chelated Zinc (EDTA). Cures yellowing of leaf veins (Khaira disease in paddy) and accelerates enzyme activation.',
      specs: {
        'Formulation': 'Zinc EDTA 12%',
        'Application': 'Foliar spray',
        'Dosage': '1 - 1.5 grams per Litre of water',
        'Recommended For': 'Paddy, Wheat, Maize, Cotton, Citrus'
      }
    },
    {
      id: 'fert-8',
      name: 'Mahadhan Calcium Nitrate + Boron (1 Kg)',
      hindiName: 'महाधन कैल्शियम नाइट्रेट + बोरॉन (1 किलो)',
      marathiName: 'महाधन कॅल्शियम नायट्रेट + बोरॉन (1 किलो)',
      category: 'fertilizers',
      shopId: 'shop-6',
      shopName: 'Balaji Krishi Rasayan',
      price: 195,
      originalPrice: 240,
      discount: '19% OFF',
      packageSize: '1 Kg Pouch',
      rating: 4.8,
      reviews: 86,
      inStock: true,
      stockCount: 75,
      featured: false,
      image: 'images/fertilizers/calcium_nitrate_1kg.jpg',
      description: 'Prevents fruit cracking, blossom end rot in tomatoes, and improves fruit firmness, color, and shelf-life.',
      specs: {
        'Nitrate Nitrogen': '15.5%',
        'Calcium': '18.8%',
        'Boron': '0.2%',
        'Recommended For': 'Tomato, Chilli, Pomegranate, Grapes, Watermelon'
      }
    },
    {
      id: 'fert-9',
      name: 'IFFCO Nano Urea (Liquid 500 ml Bottle)',
      hindiName: 'इफको नैनो यूरिया तरल (500 मि.ली.)',
      marathiName: 'इफको नॅनो युरिया लिक्विड (500 मि.ली.)',
      category: 'fertilizers',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 225,
      originalPrice: 240,
      discount: '6% OFF',
      packageSize: '500 ml Bottle',
      rating: 4.9,
      reviews: 310,
      inStock: true,
      stockCount: 110,
      featured: true,
      image: 'images/fertilizers/nano_urea_500ml.jpg',
      description: 'Revolutionary nanotechnology fertilizer! 1 bottle of 500 ml Nano Urea effectively replaces 1 full 45 kg bag of conventional urea.',
      specs: {
        'Nitrogen Content': '4.0% Total Nitrogen (w/v)',
        'Efficiency': '> 80% absorption',
        'Recommended For': 'All field crops, cereals, fruits, pulses',
        'Dosage': '2-4 ml per Litre of water during active tillering'
      }
    },
    {
      id: 'fert-10',
      name: 'Single Super Phosphate (SSP 16% P 50 Kg)',
      hindiName: 'सिंगल सुपर फास्फेट एसएसपी (50 किलो बोरी)',
      marathiName: 'सिंगल सुपर फॉस्फेट एसएसपी (50 किलो)',
      category: 'fertilizers',
      shopId: 'shop-4',
      shopName: 'Annadata Fertilizer Depot',
      price: 495,
      originalPrice: 530,
      discount: '7% OFF',
      packageSize: '50 Kg Bag',
      rating: 4.7,
      reviews: 140,
      inStock: true,
      stockCount: 45,
      featured: false,
      image: 'images/fertilizers/ssp_phosphate_50kg.jpg',
      description: 'Economical source of Phosphate (16%), Sulphur (11%), and Calcium (19%). Ideal for oilseed crops like Mustard, Groundnut, and Soybean.',
      specs: {
        'Nutrients': '16% P2O5, 11% Sulphur, 19% Calcium',
        'Form': 'Powder / Granular',
        'Recommended For': 'Oilseeds, Pulses, Legumes, Vegetables',
        'Dosage': '100-150 Kg / Acre as basal application'
      }
    },
    {
      id: 'fert-11',
      name: '100% Pure Organic Neem Cake Powder (50 Kg)',
      hindiName: 'शुद्ध जैविक नीम खली खाद (50 किलो बोरी)',
      marathiName: 'शुद्ध सेंद्रिय निंबोळी पेंड खत (50 किलो)',
      category: 'fertilizers',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 1150,
      originalPrice: 1280,
      discount: '10% OFF',
      packageSize: '50 Kg Bag',
      rating: 4.8,
      reviews: 95,
      inStock: true,
      stockCount: 35,
      featured: false,
      image: 'images/fertilizers/neem_cake_50kg.jpg',
      description: 'Dual benefit organic fertilizer and natural soil nematode repellent. Prevents white grub attack and slowly releases nitrogen.',
      specs: {
        'Nitrogen (N)': '2.5 - 3.5%',
        'Phosphorus (P)': '1.0 - 1.5%',
        'Potassium (K)': '1.4 - 2.0%',
        'Pest Protection': 'Termites, Nematodes, White grubs',
        'Dosage': '100 Kg / Acre'
      }
    },

    // --- SEEDS (8 Items) ---
    {
      id: 'seed-1',
      name: 'PBW-550 Certified Hybrid Wheat Seeds (40 Kg)',
      hindiName: 'पीबीडब्ल्यू 550 प्रमाणित गेहूं बीज (40 किलो)',
      marathiName: 'पीबीडब्ल्यू 550 प्रमाणित गहू बियाणे (40 किलो)',
      category: 'seeds',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 1450,
      originalPrice: 1600,
      discount: '9% OFF',
      packageSize: '40 Kg Bag',
      rating: 4.9,
      reviews: 512,
      inStock: true,
      stockCount: 60,
      featured: true,
      image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
      description: 'High-yielding, rust-resistant certified wheat seed variety with 140-145 days maturity. Produces bold, golden grains suitable for heavy chapatis.',
      specs: {
        'Germination Rate': '85% Minimum',
        'Genetic Purity': '98%',
        'Average Yield': '22-26 Quintals / Acre',
        'Seed Rate': '40 Kg / Acre'
      }
    },
    {
      id: 'seed-2',
      name: 'Pusa Basmati 1121 Paddy Seeds (10 Kg)',
      hindiName: 'पूसा बासमती 1121 धान बीज (10 किलो)',
      marathiName: 'पुसा बासमती 1121 भात/धान बियाणे (10 किलो)',
      category: 'seeds',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 980,
      originalPrice: 1100,
      discount: '11% OFF',
      packageSize: '10 Kg Bag',
      rating: 4.8,
      reviews: 230,
      inStock: true,
      stockCount: 35,
      featured: true,
      image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
      description: 'World-renowned extra-long grain aromatic Basmati variety with unmatched post-cooking elongation and superior market rates.',
      specs: {
        'Maturity Period': '140-145 Days',
        'Grain Length': '8.4 mm (uncooked)',
        'Recommended Sowing': 'June-July (Kharif)',
        'Seed Rate': '5-6 Kg / Acre for transplanting'
      }
    },
    {
      id: 'seed-3',
      name: 'Kranti Hybrid Mustard Seeds (1 Kg)',
      hindiName: 'क्रांति हाइब्रिड सरसों बीज (1 किलो)',
      marathiName: 'क्रांती हायब्रिड मोहरी बियाणे (1 किलो)',
      category: 'seeds',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 490,
      originalPrice: 560,
      discount: '12% OFF',
      packageSize: '1 Kg Pouch',
      rating: 4.7,
      reviews: 140,
      inStock: true,
      stockCount: 50,
      featured: false,
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
      description: 'High oil content (40%+) hybrid mustard seeds with excellent resistance against Alternaria blight and white rust.',
      specs: {
        'Oil Content': '40-42%',
        'Duration': '125-130 Days',
        'Yield Potential': '8-10 Quintals / Acre',
        'Seed Rate': '1.5-2 Kg / Acre'
      }
    },
    {
      id: 'seed-4',
      name: 'Syngenta Abhinav Hybrid Tomato Seeds (10g)',
      hindiName: 'सिंजेंटा अभिनव हाइब्रिड टमाटर बीज (10 ग्राम)',
      marathiName: 'सिंजेन्टा अभिनव हायब्रिड टोमॅटो बियाणे (10 ग्रॅम)',
      category: 'seeds',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 850,
      originalPrice: 950,
      discount: '10% OFF',
      packageSize: '10 Gram Pack',
      rating: 4.9,
      reviews: 95,
      inStock: true,
      stockCount: 40,
      featured: false,
      image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=600&q=80',
      description: 'Firm, uniform square-round deep red tomatoes with high endurance for long-distance transport and continuous harvest.',
      specs: {
        'Fruit Weight': '80-100 grams',
        'First Harvest': '60-65 days after transplant',
        'Tolerances': 'TyLCV (Tomato Yellow Leaf Curl Virus)',
        'Transplanting': '50-60 grams / Acre'
      }
    },
    {
      id: 'seed-5',
      name: 'Pioneer P3396 Hybrid Sweet Corn Seeds (5 Kg)',
      hindiName: 'पायनियर पी3396 मक्का बीज (5 किलो)',
      marathiName: 'पायोनियर पी3396 मका बियाणे (5 किलो)',
      category: 'seeds',
      shopId: 'shop-4',
      shopName: 'Annadata Fertilizer Depot',
      price: 1850,
      originalPrice: 2050,
      discount: '10% OFF',
      packageSize: '5 Kg Pack',
      rating: 4.6,
      reviews: 73,
      inStock: true,
      stockCount: 18,
      featured: false,
      image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
      description: 'Fast-maturing sweet corn hybrid with thick kernels, uniform cobs, and exceptional stalk strength.',
      specs: {
        'Cob Length': '8-9 Inches',
        'Sugar Content': 'High (Sweet & Juicy)',
        'Maturity': '75-80 Days',
        'Seed Rate': '7-8 Kg / Acre'
      }
    },
    {
      id: 'seed-6',
      name: 'JS-335 Certified Soybean Seeds (30 Kg Bag)',
      hindiName: 'जेएस-335 प्रमाणित सोयाबीन बीज (30 किलो)',
      marathiName: 'जेएस-335 प्रमाणित सोयाबीन बियाणे (30 किलो)',
      category: 'seeds',
      shopId: 'shop-5',
      shopName: 'Sahyadri Shetkari Seva Kendra',
      price: 2450,
      originalPrice: 2700,
      discount: '9% OFF',
      packageSize: '30 Kg Bag',
      rating: 4.9,
      reviews: 310,
      inStock: true,
      stockCount: 45,
      featured: true,
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
      description: 'The golden standard soybean seed variety for Maharashtra & MP. High resistance against pod shattering and stem fly.',
      specs: {
        'Germination': '70%+ Certified',
        'Duration': '95-100 Days',
        'Average Yield': '10-12 Quintals / Acre',
        'Seed Rate': '25-30 Kg / Acre'
      }
    },
    {
      id: 'seed-7',
      name: 'Prashant F1 Nashik Red Onion Seeds (500g)',
      hindiName: 'प्रशांत एफ1 नासिक लाल प्याज बीज (500 ग्राम)',
      marathiName: 'प्रशांत एफ1 नाशिक लाल कांदा बियाणे (500 ग्रॅम)',
      category: 'seeds',
      shopId: 'shop-5',
      shopName: 'Sahyadri Shetkari Seva Kendra',
      price: 1150,
      originalPrice: 1350,
      discount: '15% OFF',
      packageSize: '500 Gram Tin',
      rating: 4.8,
      reviews: 185,
      inStock: true,
      stockCount: 30,
      featured: false,
      image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80',
      description: 'Famous Nashik dark red round pungent onion variety. Outstanding storage life of 4-5 months without rotting or sprouting.',
      specs: {
        'Bulb Shape': 'Globe Deep Red',
        'Maturity': '110-120 days after transplant',
        'Seed Rate': '3-4 Kg / Acre for nursery',
        'Keeping Quality': 'Excellent'
      }
    },
    {
      id: 'seed-8',
      name: 'Vijay Desi Bengal Gram / Chana Seeds (30 Kg)',
      hindiName: 'विजय देशी चना बीज (30 किलो)',
      marathiName: 'विजय देशी हरभरा / चना बियाणे (30 किलो)',
      category: 'seeds',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 2200,
      originalPrice: 2450,
      discount: '10% OFF',
      packageSize: '30 Kg Bag',
      rating: 4.7,
      reviews: 142,
      inStock: true,
      stockCount: 38,
      featured: false,
      image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
      description: 'Drought-tolerant chickpea variety released by MPKV Rahuri. Highly resistant to Fusarium wilt with bold yellowish brown grains.',
      specs: {
        'Duration': '105-110 Days',
        'Wilt Resistance': 'High',
        'Yield': '9-11 Quintals / Acre',
        'Seed Rate': '30 Kg / Acre'
      }
    },

    // --- PESTICIDES & CROP PROTECTION (5 Items) ---
    {
      id: 'pest-1',
      name: 'Bio-Neem Gold 10,000 PPM Organic Spray (1 Litre)',
      hindiName: 'बायो नीम गोल्ड आर्गेनिक कीटनाशक (1 लीटर)',
      marathiName: 'बायो नीम गोल्ड सेंद्रिय कीटकनाशक (1 लिटर)',
      category: 'pesticides',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 650,
      originalPrice: 780,
      discount: '16% OFF',
      packageSize: '1 Litre Bottle',
      rating: 4.8,
      reviews: 210,
      inStock: true,
      stockCount: 45,
      featured: true,
      image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
      description: 'Broad-spectrum organic Azadirachtin insecticide that repels aphids, thrips, whiteflies, caterpillars without harming honeybees.',
      specs: {
        'Active Ingredient': 'Azadirachtin 1% (10,000 PPM)',
        'Safety': 'Eco-friendly, Residue Free',
        'Target Pests': 'Sucking pests, Bollworms, Leaf miners',
        'Dosage': '2.5 - 3 ml per Litre of water'
      }
    },
    {
      id: 'pest-2',
      name: 'Tata Beda (Chlorpyrifos 50% + Cypermethrin 5% EC) 1L',
      hindiName: 'टाटा बेडा कीटनाशक (1 लीटर)',
      marathiName: 'टाटा बेडा कीटकनाशक (1 लिटर)',
      category: 'pesticides',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 790,
      originalPrice: 890,
      discount: '11% OFF',
      packageSize: '1 Litre Bottle',
      rating: 4.7,
      reviews: 160,
      inStock: true,
      stockCount: 30,
      featured: false,
      image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80',
      description: 'Heavy duty dual-action contact and stomach insecticide for quick knockdown of stem borers, termites, and armyworms.',
      specs: {
        'Formulation': 'EC (Emulsifiable Concentrate)',
        'Action': 'Contact, Stomach & Vapor',
        'Target Crops': 'Paddy, Cotton, Sugarcane, Vegetables',
        'Dosage': '350-400 ml / Acre'
      }
    },
    {
      id: 'pest-3',
      name: 'UPL Saaf Fungicide (Carbendazim 12% + Mancozeb 63% WP) 500g',
      hindiName: 'यूपीएल साफ फफूंदनाशक (500 ग्राम)',
      marathiName: 'यूपीएल साफ बुरशीनाशक (500 ग्रॅम)',
      category: 'pesticides',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 360,
      originalPrice: 420,
      discount: '14% OFF',
      packageSize: '500 Gram Pouch',
      rating: 4.9,
      reviews: 340,
      inStock: true,
      stockCount: 75,
      featured: true,
      image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80',
      description: 'India\'s most trusted systemic & contact fungicide for controlling blast, leaf spot, fruit rot, and seed-borne fungal infections.',
      specs: {
        'Dual Defense': 'Systemic + Contact Action',
        'Rainfastness': 'High adherence on foliage',
        'Target Diseases': 'Leaf spot, Blast, Powdery mildew, Anthracnose',
        'Dosage': '2 grams per Litre of water'
      }
    },
    {
      id: 'pest-4',
      name: 'Bayer Confidor (Imidacloprid 17.8% SL) 250ml',
      hindiName: 'बायर कॉन्फिडोर कीटनाशक (250 मिली)',
      marathiName: 'बायर कॉन्फिडोर कीटकनाशक (250 मिली)',
      category: 'pesticides',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 590,
      originalPrice: 650,
      discount: '9% OFF',
      packageSize: '250 ml Bottle',
      rating: 4.8,
      reviews: 210,
      inStock: true,
      stockCount: 22,
      featured: false,
      image: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80',
      description: 'Systemic insecticide specifically engineered for complete control of sucking insects like jassids, aphids, and whiteflies.',
      specs: {
        'Active': 'Imidacloprid 17.8% SL',
        'Protection Period': 'Up to 15 days long-lasting control',
        'Crops': 'Cotton, Chilli, Tomato, Mango',
        'Dosage': '0.5 - 0.75 ml per Litre of water'
      }
    },
    {
      id: 'pest-5',
      name: 'FMC Coragen Insecticide (Chlorantraniliprole 18.5% SC) 60ml',
      hindiName: 'कोराजन कीटनाशक (60 मिली)',
      marathiName: 'कोराजन कीटकनाशक (60 मिली)',
      category: 'pesticides',
      shopId: 'shop-6',
      shopName: 'Balaji Krishi Rasayan',
      price: 880,
      originalPrice: 980,
      discount: '10% OFF',
      packageSize: '60 ml Bottle',
      rating: 4.9,
      reviews: 280,
      inStock: true,
      stockCount: 35,
      featured: true,
      image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
      description: 'Industry-leading Rynaxypyr active molecule for eradication of Helicoverpa, stem borers, and fall armyworm.',
      specs: {
        'Molecule': 'Rynaxypyr 18.5% SC',
        'Ovi-larvicidal': 'Kills pest eggs and larvae instantly',
        'Dosage': '0.4 ml per Litre of water (60ml / Acre)',
        'Target Crops': 'Sugarcane, Paddy, Soybean, Corn, Cotton'
      }
    },
    {
      id: 'pest-6',
      name: 'Syngenta Ampligo Insecticide (Chlorantraniliprole + Lambda) 200ml',
      hindiName: 'सिंजेंटा एम्पलिगो कीटनाशक (200 मिली)',
      marathiName: 'सिंजेंटा ॲम्प्लिगो कीटकनाशक (200 मिली)',
      category: 'pesticides',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 1150,
      originalPrice: 1280,
      discount: '10% OFF',
      packageSize: '200 ml Bottle',
      rating: 4.9,
      reviews: 195,
      inStock: true,
      stockCount: 40,
      featured: true,
      image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80',
      description: 'Syngenta Ampligo with dual-mode action delivers instant knockdown and long residual control against Helicoverpa, stem borers, and defoliators.',
      specs: {
        'Active Molecule': 'Chlorantraniliprole 9.3% + Lambda-cyhalothrin 4.6% ZC',
        'Crops': 'Soybean, Cotton, Pigeon pea, Corn, Vegetables',
        'Dosage': '80 - 100 ml per Acre',
        'Action': 'Dual Contact & Ingestion Action'
      }
    },
    {
      id: 'pest-7',
      name: 'Coromandel Fantac Plus Plant Booster & Bio-Stimulant (500ml)',
      hindiName: 'कोरोमंडल फैंटैक प्लस फसल टॉनिक (500 मिली)',
      marathiName: 'कोरोमंडल फॅन्टॅक प्लस पीक वाढ व टॉनिक (500 मिली)',
      category: 'pesticides',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 720,
      originalPrice: 850,
      discount: '15% OFF',
      packageSize: '500 ml Bottle',
      rating: 4.8,
      reviews: 230,
      inStock: true,
      stockCount: 50,
      featured: false,
      image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
      description: 'Coromandel Fantac Plus is fortified with amino acids and vitamins to stimulate vegetative growth, enhance flowering, and arrest flower and fruit dropping.',
      specs: {
        'Composition': 'Amino acids, Peptides, Plant growth stimulants',
        'Benefits': 'Increases chlorophyll, enhances fruit setting & weight',
        'Dosage': '1 - 1.5 ml per Litre of water',
        'Application': 'Foliar spray at vegetative and flowering stage'
      }
    },
    {
      id: 'pest-8',
      name: 'Godrej Double Bio-Stimulant & Flower Booster (250ml)',
      hindiName: 'गोदरेज डबल फूल व फल वर्धक टॉनिक (250 मिली)',
      marathiName: 'गोदरेज डबल फुलगळ प्रतिबंधक व उत्पादन वाढ (250 मिली)',
      category: 'pesticides',
      shopId: 'shop-4',
      shopName: 'MahaAgro Kisan Super Market',
      price: 530,
      originalPrice: 620,
      discount: '14% OFF',
      packageSize: '250 ml Bottle',
      rating: 4.8,
      reviews: 175,
      inStock: true,
      stockCount: 35,
      featured: true,
      image: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80',
      description: 'Godrej Double contains Homobrassinolide to stimulate cell division and elongation, ensuring uniform flower development, higher pod filling, and resistance to environmental stress.',
      specs: {
        'Active': 'Homobrassinolide 0.04%',
        'Key Benefit': 'Stops flower drop, increases branch flowering',
        'Target Crops': 'Cotton, Chilli, Tomato, Grapes, Pulses',
        'Dosage': '100 ml per Acre (0.5 ml / Litre)'
      }
    },
    {
      id: 'pest-9',
      name: 'Dhanuka EM-1 Caterpillar & Pod Borer Insecticide (100g)',
      hindiName: 'धनुका ईएम-1 कीटनाशक (100 ग्राम)',
      marathiName: 'धानुका ईएम-1 अळीनाशक (100 ग्रॅम)',
      category: 'pesticides',
      shopId: 'shop-6',
      shopName: 'Balaji Krishi Rasayan',
      price: 420,
      originalPrice: 480,
      discount: '12% OFF',
      packageSize: '100 Gram Pack',
      rating: 4.7,
      reviews: 140,
      inStock: true,
      stockCount: 60,
      featured: false,
      image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80',
      description: 'Dhanuka EM-1 is an advanced water-soluble granule insecticide that paralyzes and eliminates bollworms, fruit borers, and DBM within hours of ingestion.',
      specs: {
        'Technical': 'Emamectin Benzoate 5% SG',
        'Formulation': 'Soluble Granule (SG)',
        'Dosage': '0.5 gram per Litre of water (80-100g / Acre)',
        'Target Pests': 'Helicoverpa, Spodoptera, Fruit & Shoot Borer'
      }
    },
    {
      id: 'pest-10',
      name: 'Bayer Nativo Premium Broad-Spectrum Fungicide (100g)',
      hindiName: 'बायर नैटिवो फफूंदनाशक (100 ग्राम)',
      marathiName: 'बायर नॅटिव्हो बुरशीनाशक (100 ग्रॅम)',
      category: 'pesticides',
      shopId: 'shop-1',
      shopName: 'Kisan Krishi Seva Kendra',
      price: 690,
      originalPrice: 780,
      discount: '11% OFF',
      packageSize: '100 Gram Pouch',
      rating: 4.9,
      reviews: 310,
      inStock: true,
      stockCount: 28,
      featured: true,
      image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
      description: 'Bayer Nativo combines two premier fungicides to give both preventive and curative systemic control of shealth blight, blast, powdery mildew, and anthracnose.',
      specs: {
        'Composition': 'Tebuconazole 50% + Trifloxystrobin 25% WG',
        'Features': 'Quick absorption, rainfast in 2 hours, enhances grain quality',
        'Dosage': '0.8 - 1 gram per Litre of water',
        'Crops': 'Paddy, Wheat, Tomato, Mango, Grapes'
      }
    },
    {
      id: 'pest-11',
      name: 'Excel Mera 71 Systemic Non-Selective Herbicide (5 x 100g Pack)',
      hindiName: 'मेरा 71 खरपतवारनाशक (100 ग्राम x 5 पैक)',
      marathiName: 'मेरा 71 तणनाशक (100 ग्रॅम x 5 पाकीट)',
      category: 'pesticides',
      shopId: 'shop-2',
      shopName: 'Jai Kisan Agro Chemicals',
      price: 490,
      originalPrice: 550,
      discount: '11% OFF',
      packageSize: '500g Total (5 x 100g Packets)',
      rating: 4.8,
      reviews: 260,
      inStock: true,
      stockCount: 45,
      featured: false,
      image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
      description: 'Excel Mera 71 is a highly effective non-selective post-emergence herbicide for complete root-level control of stubborn perennial and annual weeds on bunds and non-crop areas.',
      specs: {
        'Active Chemical': 'Ammonium Salt of Glyphosate 71% SG',
        'Type': 'Systemic non-selective post-emergence',
        'Dosage': '100g packet per 15-16L spray pump with water',
        'Target Weeds': 'Cyperus rotundus, Cynodon dactylon, broadleaf weeds'
      }
    },

    // --- TOOLS & IRRIGATION (5 Items) ---
    {
      id: 'tool-1',
      name: 'Balwaan 16L Battery Operated Knapsack Sprayer Pump',
      hindiName: 'बलवान 16 लीटर बैटरी स्प्रेयर पंप',
      marathiName: 'बलवान 16 लिटर बॅटरी फवारणी पंप',
      category: 'tools',
      shopId: 'shop-3',
      shopName: 'GreenField Agri Inputs',
      price: 2499,
      originalPrice: 3200,
      discount: '22% OFF',
      packageSize: '1 Unit + Charger + 4 Nozzles',
      rating: 4.8,
      reviews: 185,
      inStock: true,
      stockCount: 15,
      featured: true,
      image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
      description: 'Heavy duty 12V 12Ah rechargeable battery sprayer. Sprays 25-30 tanks on single charge. Includes telescopic brass lance and pressure regulator.',
      specs: {
        'Tank Capacity': '16 Litres (Break-resistant Virgin PP)',
        'Battery Life': '6-8 hours continuous operation',
        'Pump Pressure': '100 PSI high pressure double motor',
        'Warranty': '1 Year Motor & Battery Warranty'
      }
    },
    {
      id: 'tool-2',
      name: '4-in-1 Digital Soil pH, Moisture, Sunlight & Temp Meter',
      hindiName: '4-इन-1 डिजिटल मिट्टी जांच मीटर',
      marathiName: '4-इन-1 डिजिटल माती परीक्षण मीटर',
      category: 'tools',
      shopId: 'shop-3',
      shopName: 'GreenField Agri Inputs',
      price: 799,
      originalPrice: 1199,
      discount: '33% OFF',
      packageSize: '1 Device (Battery Included)',
      rating: 4.6,
      reviews: 92,
      inStock: true,
      stockCount: 20,
      featured: false,
      image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80',
      description: 'Instant on-field testing device to check soil pH (acidity/alkalinity), moisture percentage, temperature and sunlight level before planting.',
      specs: {
        'pH Range': '3.5 to 9.0 pH',
        'Probe Length': '200 mm high sensitivity probe',
        'Display': 'Backlit LCD with auto shut-off',
        'Calibration': 'Pre-calibrated'
      }
    },
    {
      id: 'tool-3',
      name: 'Micro Drip Irrigation Kit for 100 Plants / Trees',
      hindiName: 'माइक्रो ड्रिप सिंचाई किट (100 पौधे)',
      marathiName: 'मायक्रो ठिबक सिंचन किट (100 झाडे)',
      category: 'tools',
      shopId: 'shop-3',
      shopName: 'GreenField Agri Inputs',
      price: 1399,
      originalPrice: 1899,
      discount: '26% OFF',
      packageSize: 'Complete DIY Set with 50m Main Line',
      rating: 4.7,
      reviews: 64,
      inStock: true,
      stockCount: 12,
      featured: false,
      image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80',
      description: 'Saves up to 70% irrigation water. Delivers water directly to roots with adjustable drippers. Ideal for vegetables, fruit orchards, and polyhouses.',
      specs: {
        'Main Pipe': '16mm UV-resistant LDPE (50 meters)',
        'Drippers': '100 Adjustable 0-70 LPH drippers',
        'Fittings': 'Connectors, T-joints, End caps, Punch tool included',
        'Water Pressure': '1.0 - 2.5 kg/cm²'
      }
    },
    {
      id: 'tool-4',
      name: 'Falcon Professional Heavy Duty Garden Pruner & Cutter',
      hindiName: 'फाल्कन प्रूनर एवं कटर',
      marathiName: 'फाल्कन हेवी ड्युटी छाटणी कात्री व कटर',
      category: 'tools',
      shopId: 'shop-3',
      shopName: 'GreenField Agri Inputs',
      price: 450,
      originalPrice: 550,
      discount: '18% OFF',
      packageSize: '1 Piece (8.5 Inch)',
      rating: 4.9,
      reviews: 135,
      inStock: true,
      stockCount: 30,
      featured: false,
      image: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=600&q=80',
      description: 'SK-5 high carbon hardened Japanese steel bypass blade for clean branch cutting, grafting, harvesting, and vine maintenance.',
      specs: {
        'Blade Material': 'Teflon coated SK-5 Steel',
        'Cutting Capacity': 'Up to 20mm branch diameter',
        'Handle': 'Ergonomic non-slip rubber grip',
        'Lock': 'Safety thumb lock'
      }
    },
    {
      id: 'tool-5',
      name: 'Automatic Solar LED Insect Light Trap for Pest Control',
      hindiName: 'सोलर कीट नियंत्रण लाइट ट्रैप',
      marathiName: 'सौर ऊर्जा कीड नियंत्रण लाइट ट्रॅप',
      category: 'tools',
      shopId: 'shop-3',
      shopName: 'GreenField Agri Inputs',
      price: 1899,
      originalPrice: 2499,
      discount: '24% OFF',
      packageSize: '1 Solar Unit + Stand',
      rating: 4.8,
      reviews: 82,
      inStock: true,
      stockCount: 14,
      featured: true,
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
      description: 'Eco-friendly nocturnal pest control. Attracts moths, borers, and flying beetles via ultraviolet wavelength with zero electricity cost.',
      specs: {
        'Solar Panel': '5 Watt High Efficiency Polycrystalline',
        'Operation': 'Auto on at dusk, auto off after 4 hours',
        'Coverage': '1 to 1.5 Acre per unit',
        'Safety': 'Safe for friendly honeybees'
      }
    }
  ],

  // Crop dosage calculation references (Per Acre)
  dosageGuides: {
    wheat: {
      cropName: 'Wheat (गेहूं)',
      cropNameHi: 'गेहूं (Wheat)',
      cropNameMr: 'गहू (Wheat)',
      ureaBags: 2.5,
      dapBags: 1.0,
      mopBags: 0.5,
      seedKg: 40,
      waterTimes: '4-5 Irrigations',
      tip: 'Apply 1 bag DAP + 1 bag Urea at sowing; top dress remaining Urea in 2 split doses before 1st & 2nd watering.',
      tipHi: 'बुवाई के समय 1 बोरी डीएपी + 1 बोरी यूरिया डालें; बाकी यूरिया पहली और दूसरी सिंचाई से पहले दो बार में दें।',
      tipMr: 'पेरणीच्या वेळी 1 गोणी डीएपी + 1 गोणी युरिया द्या; उर्वरित युरिया पहिल्या व दुसऱ्या पाळीपूर्वी दोन हप्त्यांत द्या.'
    },
    paddy: {
      cropName: 'Paddy / Rice (धान)',
      cropNameHi: 'धान / चावल (Paddy)',
      cropNameMr: 'भात / धान (Paddy)',
      ureaBags: 3.0,
      dapBags: 1.0,
      mopBags: 0.6,
      seedKg: 6,
      waterTimes: 'Continuous standing water',
      tip: 'Incorporate DAP and Potash during puddled field preparation. Apply Zinc Sulphate (10kg/acre) 15 days after transplant.',
      tipHi: 'खेत की तैयारी के समय डीएपी और पोटाश मिलाएं। रोपाई के 15 दिन बाद जिंक सल्फेट (10 किग्रा/एकड़) डालें।',
      tipMr: 'चिखलणीच्या वेळी डीएपी व पोटॅश जमिनीत मिसळा. पुनर्लागवडीनंतर 15 दिवसांनी झिंक सल्फेट (10 किलो/एकर) द्या.'
    },
    soybean: {
      cropName: 'Soybean (सोयाबीन)',
      cropNameHi: 'सोयाबीन (Soybean)',
      cropNameMr: 'सोयाबीन (Soybean)',
      ureaBags: 0.8,
      dapBags: 1.2,
      mopBags: 0.5,
      seedKg: 28,
      waterTimes: 'Rainfed / 1-2 protective irrigations',
      tip: 'Treat seeds with Rhizobium & Trichoderma before sowing. Apply 10kg Sulphur with DAP for higher oil and protein content.',
      tipHi: 'बुवाई पूर्व बीज को राइजोबियम से उपचारित करें। अधिक तेल के लिए 10 किग्रा सल्फर जरूर डालें।',
      tipMr: 'पेरणीपूर्वी बियाण्यास रायझोबियमची बीजप्रक्रिया करा. दाण्यांत तेल व प्रथिनांचे प्रमाण वाढवण्यासाठी 10 किलो गंधक (सल्फर) द्या.'
    },
    gram: {
      cropName: 'Bengal Gram / Harbhara (चना)',
      cropNameHi: 'चना / छोले (Gram)',
      cropNameMr: 'हरभरा / चणा (Gram)',
      ureaBags: 0.5,
      dapBags: 1.0,
      mopBags: 0.4,
      seedKg: 30,
      waterTimes: '1-2 Irrigations (Branching & Pod filling)',
      tip: 'Avoid excess nitrogen to prevent vegetative overgrowth. Spray 19:19:19 + Boron during flowering.',
      tipHi: 'अधिक यूरिया न डालें जिससे वानस्पतिक वृद्धि ज्यादा न हो। फूल आते समय 19:19:19 का छिड़काव करें।',
      tipMr: 'जास्त नत्र (युरिया) देऊ नका, अन्यथा झाडांची अनावश्यक वाढ होते. फुलोरा अवस्थेत 19:19:19 ची फवारणी करा.'
    },
    mustard: {
      cropName: 'Mustard (सरसों)',
      cropNameHi: 'सरसों (Mustard)',
      cropNameMr: 'मोहरी (Mustard)',
      ureaBags: 1.5,
      dapBags: 0.8,
      mopBags: 0.3,
      seedKg: 1.5,
      waterTimes: '2 Irrigations',
      tip: 'Mustard responds very well to Sulphur. Mix 10kg Bentonite Sulphur with DAP for higher oil percentage.',
      tipHi: 'सरसों में सल्फर का बहुत लाभ होता है। अधिक तेल प्रतिशत के लिए डीएपी के साथ 10 किग्रा बेंटोनाइट सल्फर मिलाएं।',
      tipMr: 'मोहरीला गंधकाचा (सल्फर) मोठा फायदा होतो. तेलाचे प्रमाण वाढवण्यासाठी डीएपीसोबत 10 किलो बेंटोनाइट सल्फर मिसळा.'
    },
    cotton: {
      cropName: 'Cotton (कपास)',
      cropNameHi: 'कपास (Cotton)',
      cropNameMr: 'कापूस (Cotton)',
      ureaBags: 3.5,
      dapBags: 1.2,
      mopBags: 0.8,
      seedKg: 2,
      waterTimes: 'Based on rainfall/drip',
      tip: 'Do split application of Urea. Spray 19:19:19 + Boron during flowering and boll formation.',
      tipHi: 'यूरिया को 3-4 बार में दें। फूल और गूलर बनते समय 19:19:19 + बोरॉन का छिड़काव करें।',
      tipMr: 'युरिया विभागून द्या. फुले व बोंडे लागण्याच्या काळात 19:19:19 + बोरॉनची फवारणी करा.'
    },
    potato: {
      cropName: 'Potato (आलू)',
      cropNameHi: 'आलू (Potato)',
      cropNameMr: 'बटाटा (Potato)',
      ureaBags: 4.0,
      dapBags: 2.0,
      mopBags: 1.5,
      seedKg: 1200,
      waterTimes: 'Weekly light irrigation',
      tip: 'Potato requires high Potash for tuber swelling and skin finish. Avoid excess Nitrogen late in season.',
      tipHi: 'कंद के अच्छे आकार के लिए अधिक पोटाश जरूरी है। फसल के अंतिम दौर में अधिक यूरिया न डालें।',
      tipMr: 'बटाट्याचा आकार व चकाकीसाठी पोटॅश आवश्यक आहे. शेवटच्या टप्प्यात जास्त नत्र (युरिया) देणे टाळा.'
    },
    sugarcane: {
      cropName: 'Sugarcane (गन्ना/ऊस)',
      cropNameHi: 'गन्ना (Sugarcane)',
      cropNameMr: 'ऊस (Sugarcane)',
      ureaBags: 5.5,
      dapBags: 2.5,
      mopBags: 2.0,
      seedKg: 2500,
      waterTimes: 'Every 10-12 days',
      tip: 'Heavy feeder crop. Apply split doses of Urea at 45, 90, and 120 days with earthing-up (माती लावणे).',
      tipHi: 'गन्ने में 45, 90 और 120 दिनों में यूरिया की किश्तें डालें और मिट्टी अवश्य चढ़ाएं।',
      tipMr: 'मोठ्या प्रमाणात अन्नद्रव्ये लागणारे पीक. 45, 90 व 120 दिवसांनी युरियाचे हप्ते देऊन मोठी बाळबांधणी (माती लावणे) करा.'
    }
  },

  // Promo Banners for home slider
  banners: [
    {
      id: 'b1',
      title: 'Rabi Season Special Seed Offer',
      titleHi: 'रबी सीजन प्रमाणित बीज विशेष छूट',
      titleMr: 'रब्बी व खरीप हंगाम बियाणे विशेष सूट',
      subtitle: 'Certified PBW-550 Wheat, JS-335 Soybean & Mustard Seeds',
      subtitleHi: 'सरकारी दरों पर प्रमाणित गेहूं, सोयाबीन व सरसों बीज सीधे नजदीकी मंडी से',
      subtitleMr: 'शासकीय दरांवर प्रमाणित गहू, सोयाबीन व कांदा बियाणे थेट नजीकच्या कृषी केंद्रातून',
      badge: 'Up to 25% OFF',
      badgeHi: '25% तक छूट',
      badgeMr: '25% पर्यंत सूट',
      color: 'linear-gradient(135deg, #15803d 0%, #166534 100%)',
      btnText: 'Shop Certified Seeds',
      btnTextHi: 'प्रमाणित बीज खरीदें',
      btnTextMr: 'प्रमाणित बियाणे खरेदी करा',
      filterCategory: 'seeds'
    },
    {
      id: 'b2',
      title: 'Express 45-Min Fertilizer Delivery',
      titleHi: '45 मिनट में त्वरित खाद डिलीवरी',
      titleMr: '45 मिनिटांत जलद खत डिलिव्हरी',
      subtitle: 'IFFCO Urea, DAP, Mahadhan & Water-Soluble NPK at your farm gate',
      subtitleHi: 'इफको यूरिया, डीएपी, महाधन और 19:19:19 सीधे आपके खेत तक',
      subtitleMr: 'इफको युरिया, डीएपी, महाधन आणि विद्राव्य एनपीके थेट तुमच्या शेतापर्यंत',
      badge: 'Local Shop Fast Delivery',
      badgeHi: 'दुकान से सीधी डिलीवरी',
      badgeMr: 'स्थानिक दुकानातून जलद पोहोच',
      color: 'linear-gradient(135deg, #047857 0%, #064e3b 100%)',
      btnText: 'Order Fertilizers',
      btnTextHi: 'उर्वरक आर्डर करें',
      btnTextMr: 'खते ऑर्डर करा',
      filterCategory: 'fertilizers'
    },
    {
      id: 'b3',
      title: 'Smart Crop Protection',
      titleHi: 'सुरक्षित फसल - भरपूर पैदावार',
      titleMr: 'स्मार्ट पीक संरक्षण - भरघोस उत्पादन',
      subtitle: 'FMC Coragen, Bio-Neem Gold and UPL Saaf for total pest control',
      subtitleHi: 'कोराजन, जैविक नीम तेल एवं यूपीएल साफ से कीट व फफूंद से फसल बचाएं',
      subtitleMr: 'कोराजन, बायो-नीम व यूपीएल साफने कीड आणि बुरशीपासून पिकांचे रक्षण करा',
      badge: 'Organic & Certified',
      badgeHi: 'जैविक व सुरक्षित',
      badgeMr: 'सेंद्रिय व प्रमाणित',
      color: 'linear-gradient(135deg, #b45309 0%, #78350f 100%)',
      btnText: 'View Crop Defense',
      btnTextHi: 'कीटनाशक देखें',
      btnTextMr: 'कीटकनाशके पहा',
      filterCategory: 'pesticides'
    }
  ]
};
